Change libgrav to libgrav_common

diff --git a/lib/libgrav_core b/lib/libgrav_core
--- a/lib/libgrav_core
+++ b/lib/libgrav_core
@@ -3,7 +3,7 @@
 #
 # Public: get_core() function for grav-core.sh get script.
 #
-function libgrav_core::get_core() { # Public: get_core() function for grav-core.sh get script.
+function libgrav_core::get_core() { #-# Public: get_core() function for grav-core.sh get script.
    local _RC=0
    local _GRAV_CMD="${1}"
    local _GRAV_CORE="${2}"
@@ -26,7 +26,7 @@ function libgrav_core::get_core() { # Public: get_core() function for grav-core.
       dev)
          _GRAV_DEV=$(cat "${CFG_DIR}"/.config.dev | tr -d '"' | cut -d'=' -f2)
          _GRAV_OUTPUT="${ROOT_DIR}/tmp/grav/core/${_GRAV_NAME}-${_GRAV_DEV}?testing.zip"
-         if [[ -e "${_GRAV_OUTPUT}" ]]; then libgrav::error 2 "Error: File ${_GRAV_OUTPUT} exists, download not needed."; fi
+         if [[ -e "${_GRAV_OUTPUT}" ]]; then libgrav::common error 2 "Error: File ${_GRAV_OUTPUT} exists, download not needed." "${NAME}"; fi
 
          wget -O "${_GRAV_OUTPUT}" \
             ${_GRAV_URL}/core/${_GRAV_NAME}/${_GRAV_DEV}?testing
@@ -34,7 +34,7 @@ function libgrav_core::get_core() { # Public: get_core() function for grav-core.
 
       [0-9]*.[0-9]*.[0-9]*-[a-z][a-z].[0-9]*)
          _GRAV_OUTPUT="${ROOT_DIR}/tmp/grav/core/${_GRAV_NAME}-${_GRAV_CORE}?testing.zip"
-         if [[ -e "${_GRAV_OUTPUT}" ]]; then libgrav::error 2 "Error: File ${_GRAV_OUTPUT} exists, download not needed."; fi
+         if [[ -e "${_GRAV_OUTPUT}" ]]; then libgrav::common error 2 "Error: File ${_GRAV_OUTPUT} exists, download not needed." "${NAME}"; fi
 
          wget -O "${_GRAV_OUTPUT}" \
             ${_GRAV_URL}/core/${_GRAV_NAME}/${_GRAV_CORE}?testing
@@ -43,7 +43,7 @@ function libgrav_core::get_core() { # Public: get_core() function for grav-core.
       prod)
          _GRAV_PROD=$(cat "${CFG_DIR}"/.config.prod | tr -d '"' | cut -d'=' -f2)
          _GRAV_OUTPUT="${ROOT_DIR}/tmp/grav/core/${_GRAV_NAME}-${_GRAV_PROD}.zip"
-         if [[ -e "${_GRAV_OUTPUT}" ]]; then libgrav::error 2 "Error: File ${_GRAV_OUTPUT} exists, download not needed."; fi
+         if [[ -e "${_GRAV_OUTPUT}" ]]; then libgrav::common error 2 "Error: File ${_GRAV_OUTPUT} exists, download not needed." "${NAME}"; fi
 
          wget -O "${_GRAV_OUTPUT}" \
             ${_GRAV_URL}/core/${_GRAV_NAME}/${_GRAV_PROD}
@@ -51,16 +51,20 @@ function libgrav_core::get_core() { # Public: get_core() function for grav-core.
       
       [0-9]*.[0-9]*.[0-9]*)
          _GRAV_OUTPUT="${ROOT_DIR}/tmp/grav/core/${_GRAV_NAME}-${_GRAV_CORE}.zip"
-         if [[ -e "${_GRAV_OUTPUT}" ]]; then libgrav::error 2 "Error: File ${_GRAV_OUTPUT} exists, download not needed."; fi
+         if [[ -e "${_GRAV_OUTPUT}" ]]; then libgrav::common error 2 "Error: File ${_GRAV_OUTPUT} exists, download not needed." "${NAME}"; fi
 
          wget -O "${_GRAV_OUTPUT}" \
             ${_GRAV_URL}/core/${_GRAV_NAME}/${_GRAV_CORE}
       ;;
 
-      *) libgrav::error 2 "Error: Argument is not defined: ${_GRAV_CORE}!"
+      *) libgrav::common error 2 "Error: Argument is not defined: ${_GRAV_CORE}!" "${NAME}"
       ;;
 
    esac
+
+   _RC=$?
+
+   if [ ${_RC} -eq 0 ]; then libgrav::common help " Info: Download of ${_GRAV_NAME}-${_GRAV_CORE}.zip in ${ROOT_DIR} was successful." "${NAME}"; fi
 
    return ${_RC}
 }
@@ -68,7 +72,7 @@ function libgrav_core::get_core() { # Public: get_core() function for grav-core.
 #
 # Public: set_core() function for grav-core.sh set script.
 #
-libgrav_core::set_core() { # Public: set_core() function for grav-core.sh set script.
+function libgrav_core::set_core() { #-# Public: set_core() function for grav-core.sh set script.
    local _RC=0
    local _GRAV_CMD="${1}"
    local _GRAV_CORE="${2}"
@@ -94,14 +98,14 @@ libgrav_core::set_core() { # Public: set_core() function for grav-core.sh set sc
          echo "GRAV_PROD=${_GRAV_CORE}"  > "${CFG_DIR}"/.config.prod 
       ;;
 
-      *) libgrav::error 2 "Error: Argument is not defined: ${_GRAV_CORE}!"
+      *) libgrav::common error 2 "Error: Argument is not defined: ${_GRAV_CORE}!" "${NAME}"
       ;;
 
    esac
 
    _RC=$?
 
-   if [ ${_RC} -eq 0 ]; then libgrav::help " Info: Download now the respective grav core package with ${BIN_DIR}/grav-core.sh get"; fi
+   if [ ${_RC} -eq 0 ]; then libgrav::common help " Info: Download now the respective grav core package with ${BIN_DIR}/grav-core.sh get" "${NAME}"; fi
 
    return ${_RC}
 }
